# environment variables
environment:
  matrix:
  - nodejs_version: "0.12"
  
# to add several platforms to build matrix:
platform:
  - x64


before_build:
  - cmd: echo Building
  - cmd: npm install -g node-gyp
  - cmd: echo Build done

install:
  - cmd: echo Installing external tools
  - ps: Install-Product node 0.12 x64
  - cmd: echo node installed

build_script:
  - cmd: npm install -msvs_version=2012
  - cmd: ./node_modules/gulp/bin/gulp.js

