# environment variables
environment:
  matrix:
  - nodejs_version: "0.12"
  
# to add several platforms to build matrix:
platform:
  - x64
  - x32

install:
  - cmd: echo Starting build
  - cmd: npm install -g node-gyp
  - cmd: npm install
