/**
 * Created by Praveen on 06/11/2015.
 */

export const UPDATE_CACHE = 'UPDATE_CACHE';

export const REMOVE_DEVICE_FROM_CACHE = 'REMOVE_DEVICE_FROM_CACHE';

export const CREATE_DEVICE_IN_CACHE = 'CREATE_DEVICE_IN_CACHE';

export const MODIFY_TRANSIENT = 'MODIFY_TRANSIENT';

export const MODIFY_PERSISTENT = 'MODIFY_PERSISTENT';
